version: "3.3"
services:
  web:
    build: .
    container_name: php74
    links:
      - db:mariadb
    volumes:
      - ../:/var/www/html/
    ports:
      - 8000:80
  db:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
